export const colorOptions = [
    { value: 'Blanco', label: 'Blanco' },
    { value: 'Negro', label: 'Negro' },
    { value: 'Gris', label: 'Gris' },
    { value: 'Plateado', label: 'Plateado' },
    { value: 'Dorado', label: 'Dorado' },
    { value: 'Beige', label: 'Beige' },
    { value: 'Azul', label: 'Azul' },
    { value: 'Rojo', label: 'Rojo' },
    { value: 'Verde', label: 'Verde' },
    { value: 'Amarillo', label: 'Amarillo' },
    { value: 'Café', label: 'Café' },
    { value: 'Champán', label: 'Champán' },
    { value: 'Bronce', label: 'Bronce' },
    { value: 'Anaranjado', label: 'Anaranjado' },
    { value: 'Morado', label: 'Morado' },
    { value: 'Turquesa', label: 'Turquesa' },
    { value: 'Rosado', label: 'Rosado' },
    { value: 'Otro', label: 'Otro' },
  ];
  